[phases.setup]
nixPkgs = [
  "python39", 
  "python39Packages.pip", 
  "gcc", 
  "postgresql", 
  "libffi", 
  "openssl", 
  "zlib", 
  "libjpeg", 
  "freetype", 
  "libxml2", 
  "libxslt", 
  "make"
]

[phases.install]
cmds = ["pip install -v -r requirements.txt"]

[phases.build]
cmds = ["# Add any build commands here if needed"]

[start]
cmd = "python Tammeny_Mainapi.py"
